export const db = "main-stackoverflow"
export const questionCollection = "question"
export const answerCollection = "answer"
export const commentCollection = "comment"
export const voteCollection = "vote"
export const questionAttachmentBucket = "question-attachment"
